version: '3'
services:
  app:
    container_name: nextjs
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./:/app:cached
      - node_modules_volume:/app/node_modules
    ports:
      - '3001:3001'
    init: true
    command: npm run dev
volumes:
  node_modules_volume:
