steps:
  - id: 'Build Image'
    name: 'gcr.io/cloud-builders/docker'
    args: [ "build",
            "-t", "gcr.io/$PROJECT_ID/$_APP_NAME:$SHORT_SHA",
            "-t", "gcr.io/$PROJECT_ID/$_APP_NAME:latest",
            "--cache-from", "gcr.io/$PROJECT_ID/$_APP_NAME:latest",
            "$_BUILD_CONTEXT" ]

  - id: "Push Image"
    name: "gcr.io/cloud-builders/docker"
    args: [ "push", "gcr.io/$PROJECT_ID/$_APP_NAME" ]

images:
  - 'gcr.io/$PROJECT_ID/$_APP_NAME:latest'
tags: [ 'cloud-builders-community' ]