steps:
    - id: 'Build Image'
      name: 'gcr.io/cloud-builders/docker'
      args:
          [
              'build',
              '-t',
              'gcr.io/$PROJECT_ID/$_APP_NAME:$SHORT_SHA',
              '-t',
              'gcr.io/$PROJECT_ID/$_APP_NAME:latest',
              '--cache-from',
              'gcr.io/$PROJECT_ID/$_APP_NAME:latest',
              '$_BUILD_CONTEXT',
          ]
      timeout: 2000s

    - id: 'Push Image'
      name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/$_APP_NAME']
      timeout: 2000s

    - id: 'Deploy App'
      name: 'gcr.io/cloud-builders/gcloud'
      args:
          [
              'run',
              'deploy',
              '$_APP_NAME',
              '--image',
              'gcr.io/$PROJECT_ID/$_APP_NAME:latest',
              '--region',
              'asia-northeast1',
              '--platform',
              'managed',
          ]
      timeout: 2000s

timeout: 3600s

images:
    - 'gcr.io/$PROJECT_ID/$_APP_NAME:latest'
tags: ['cloud-builders-community']
