steps:
  - id: 'Deploy App'
    name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'run', 'deploy', '$_APP_NAME', '--image', 'gcr.io/$PROJECT_ID/$_APP_NAME:latest', '--region', 'asia-northeast1', '--platform', 'managed' ]